data_path: '/n/data1/hms/dbmi/rajpurkar/lab/datasets/MAIDA-NICU/preprocessed_vish/new_annotations'
output_path : '/home/vir247/scratch/nicu/MAIDA-continual-learning/outputs'
annos_dir: '/n/data1/hms/dbmi/rajpurkar/lab/datasets/MAIDA-NICU/preprocessed_vish/new_annotations/annotations_640x640_latest'
train_annos_path: '/n/data1/hms/dbmi/rajpurkar/lab/datasets/MAIDA-NICU/preprocessed_vish/new_annotations/annotations_640x640_latest/SES-train-annotations.json'
test_annos_path: '/n/data1/hms/dbmi/rajpurkar/lab/datasets/MAIDA-NICU/preprocessed_vish/new_annotations/annotations_640x640_latest/SES-test-annotations.json'

use_all-but-target-hospital_only: False
target_hospital: 'SES'
use_all-but-target-hospital_only: False
use_all-hospitals: False
model_name: 'CarinaNet'
number_of_simulation: 10
model_path: "" # Default model is saved in the corresponding model folder
