data_path: '/home/vir247/scratch/nicu/MAIDA-NICU/prepared_data'
output_path : '/home/vir247/scratch/nicu/MAIDA-continual-learning/outputs'
annos_dir: '/home/vir247/scratch/nicu/MAIDA-NICU/prepared_data/annotations_640x640_latest'
train_annos_path: '/home/vir247/scratch/nicu/MAIDA-NICU/prepared_data/annotations_640x640_latest/Childrens-Hospital-Colorado-train-annotations.json'
test_annos_path: '/home/vir247/scratch/nicu/MAIDA-NICU/prepared_data/annotations_640x640_latest/Childrens-Hospital-Colorado-test-annotations.json'

use_all-but-target-hospital_only: True
target_hospital: 'Childrens-Hospital-Colorado'
use_all-but-target-hospital_only: False
use_all-hospitals: False
model_name: 'CarinaNet'
number_of_simulation: 10
model_path: "" # Default model is saved in the corresponding model folder